dm: i2c: lx2160: Revert lx2160 i2c dm support patch set
lx2160 i2c dm support patch-set causes the compilation failure
for lx2160aqds board, So we need to revert these patches (commit id:
8c2914d5 - e76efe59).

Below is the compilation error while compiling for lx2160aqds,
cmd/i2c.c:218:9: error: 'CONFIG_SYS_I2C_SPEED' undeclared (first use in
this function); did you mean 'CONFIG_SYS_I2C_SLAVE'?
  return CONFIG_SYS_I2C_SPEED;
           ^~~~~~~~~~~~~~~~~~~~
	   CONFIG_SYS_I2C_SLAVE

Signed-off-by: Chuanhua Han <chuanhua.han@nxp.com>